name: barbershop_app
description: Uma nova aplicação Flutter.

publish_to: 'none' # Remova esta linha se publicar o app na pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0    
  material_design_icons_flutter: ^5.0.0  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imgfundo.png
    - assets/adomicilio.png
    - assets/degrade.png
    - assets/sobrancelha.png
    - assets/barba.png
    - assets/logo.png
    - assets/barber1.png
    - assets/barber2.png
    - assets/barber3.png
    - assets/barber4.png
    - assets/barber5.png